### ISSUE TITLE
Create a README describing how to run and contribute to the project

### ISSUE THREAD

**Issue by zenorocha** [liferay/com-liferay-vulcan#61]
Hello @ahdezma! @milendyankov, @sammonsjl and I would like to run this project locally to better understand it. Is it possible to describe the steps to run it so external people can also contribute?

**Comment by ahdezma** [comment]
Hi @zenorocha 

Would you like to know how to run it inside a Liferay container to test functionality?

**Comment by nhpatt** [comment]
We have our first draft of the README: https://github.com/liferay/com-liferay-vulcan 🎉 

We'll release an update after the name change, any feedback is welcomed 😄

**Comment by JorgeFerrer** [comment]
👏

**Comment by zenorocha** [comment]
Great!

**Comment by sammonsjl** [comment]
Awesome!

**Comment by lemacedo** [comment]
:+1:
